server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: hoteler
    password: 267552
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    baseline-on-migrate: true
    clean-on-validation-error: true