services:
  mysql:
    image: mysql:9.1.0
    container_name: hoteler-mysql-9
    volumes:
      - hoteler-mysql-volume:/var/lib/mysql
      - ./database/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hoteler
      MYSQL_USER: hoteler
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    # command: --default-character-set=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - hoteler-network

  postgres:
    image: postgres:17.2-alpine3.20
    container_name: hoteler-postgres-16.3
    ports:
      - 5432:5432
    volumes:
      - hoteler-postgres-volume:/var/lib/postgresql/data
      - ./database/postgtres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
    networks:
      - hoteler-network
  nacos:
    image: qingpan/rnacos:v0.5.20
    container_name: hoteler-nacos-2.4.0
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    volumes:
      - hoteler-nacos-volume:/io:rw
    environment:
      - RNACOS_INIT_ADMIN_USERNAME=admin
      - RNACOS_INIT_ADMIN_PASSWORD=admin
      - RNACOS_HTTP_PORT=8848
    restart: always
    networks:
      - hoteler-network
#  nacos:
#    image: nacos/nacos-server:v2.4.0-slim
#    container_name: hoteler-nacos-2.4.0
#    privileged: true
#    restart: always
#    environment:
#      - TZ=Asia/Shanghai
#      - MODE=standalone
#      - SPRING_DATASOURCE_PLATFORM=mysql
#      - MYSQL_SERVICE_HOST=mysql
#      - MYSQL_SERVICE_PORT=3306
#      - MYSQL_SERVICE_USER=root
#      - MYSQL_SERVICE_PASSWORD=123456
#      - MYSQL_SERVICE_DB_NAME=nacos
#      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#      - JVM_XMS=512m
#      - JVM_XMX=512m
#      - JVM_XMN=512m
#    ports:
#      - "8848:8848"
#      - "9848:9848"
#      - "9849:9849"
#    depends_on:
#      - mysql
#    networks:
#      - hoteler-network
  bytebase:
    image: bytebase/bytebase:3.2.0
    container_name: hoteler-bytebase-2.22.0
    restart: always
    ports:
      - 5678:5678
    # # Uncomment the following lines to persist data
    volumes:
       - hoteler-bytebase-volume:/var/opt/bytebase
    command: [ "--data", "/var/opt/bytebase", "--port", "5678", "--pg", "postgresql://postgres:123456@postgres:5432/bytebase?sslmode=disable" ]
    depends_on:
      - postgres
    networks:
      - hoteler-network

  prometheus:
    image: bitnami/prometheus:2.55.1
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - hoteler-network

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - '13000:3000'
    depends_on:
      - prometheus
    networks:
      - hoteler-network

volumes:
  hoteler-mysql-volume:
    external: true
  hoteler-postgres-volume:
    external: true
  hoteler-bytebase-volume:
    external: true
  hoteler-nacos-volume:
    external: true

networks:
  hoteler-network:
    external: true