services:
  mysql:
    image: mysql:9.5.0
    container_name: mysql-8
    volumes:
      - hoteler-mysql-volume:/var/lib/mysql
      # - ./database/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hoteler
      MYSQL_USER: hoteler
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - hoteler-network

  postgres:
    image: postgres:17.5-alpine3.20
    container_name: hoteler-postgres-17
    ports:
      - 5432:5432
    volumes:
      - hoteler-postgres-volume:/var/lib/postgresql/data
      - ./database/postgtres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
    networks:
      - hoteler-network
  nacos:
    image: qingpan/rnacos:v0.7.2
    container_name: hoteler-qingpan-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    volumes:
      - hoteler-nacos-volume:/io:rw
    environment:
      - RNACOS_INIT_ADMIN_USERNAME=admin
      - RNACOS_INIT_ADMIN_PASSWORD=admin
      - RNACOS_HTTP_PORT=8848
    restart: always
    networks:
      - hoteler-network
  bytebase:
    image: bytebase/bytebase:3.10.1
    container_name: hoteler-bytebase-3
    restart: always
    ports:
      - 5678:5678
    # # Uncomment the following lines to persist data
    volumes:
       - hoteler-bytebase-volume:/var/opt/bytebase
    command: [ "--data", "/var/opt/bytebase", "--port", "5678", "--pg", "postgresql://postgres:123456@postgres:5432/bytebase?sslmode=disable" ]
    depends_on:
      - postgres
    networks:
      - hoteler-network

  prometheus:
    image: bitnami/prometheus:3.0.1
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - hoteler-network

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - '13000:3000'
    depends_on:
      - prometheus
    networks:
      - hoteler-network

volumes:
  hoteler-mysql-volume:
    external: true
  hoteler-postgres-volume:
    external: true
  hoteler-bytebase-volume:
    external: true
  hoteler-nacos-volume:
    external: true

networks:
  hoteler-network:
    external: true