version: '3'
services:
  mysql:
    image: mysql:8.0.31
    container_name: hoteler-mysql-8.0
    volumes:
      - hoteler-mysql-volume:/var/lib/mysql
      - ./database/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 267552
      MYSQL_DATABASE: hoteler
      MYSQL_USER: hoteler
      MYSQL_PASSWORD: 267552
    ports:
      - "3306:3306"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]
    networks:
      - hoteler-network

  postgres:
    image: postgres:15.2
    container_name: hoteler-postgres-15.2
    ports:
      - 5432:5432
    volumes:
      - hoteler-postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hoteler
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
    networks:
      - hoteler-network

  nacos:
    image: nacos/nacos-server:v2.2.0
    # https://github.com/alibaba/nacos/issues/6340
    # image: zhusaidong/nacos-server-m1:2.0.3
    container_name: hoteler-nacos-2.2.0
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=267552
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=512m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - mysql
    networks:
      - hoteler-network

volumes:
  hoteler-mysql-volume:
    external: true
  hoteler-postgres-volume:
    external: true

networks:
  hoteler-network:
    external: true