server:
  port: 8091
spring:
  application:
    name: worker-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/worker
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    baseline-on-migrate: true
  devtools:
    restart:
      enabled: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            # class: org.daming.hoteler.worker.config.threadpool.SimpleVirtualThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    auto-startup: true # Quartz 是否自动启动
    startup-delay: 0 # 延迟 N 秒启动
    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    overwrite-existing-jobs: false # 是否覆盖已有 Job 的配置
logging:
  level:
    root: info