server:
  port: 8089
spring:
  application:
    name: workflow-service
  datasource:
    url: jdbc:postgresql://192.168.31.220:5432/hoteler
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: 192.168.31.220:8848
  flyway:
    skip-executing-migrations: true
logging:
  level:
    root:
      info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show:
      details: always