server:
  port: 8088
spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/hoteler?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: hoteler
    password: 267552
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    baseline-on-migrate: true
    clean-on-validation-error: true
secret:
  salt: dc513dcf1de6941978deb973fe98c1f6
  key: damingerdai22
  personSalt: dc513dcf1de6941978deb973fe98c1f3