name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY_NAME: github.com

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version: [ 21 ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run:  ./mvnw package -Dmaven.test.skip=true
      - name: Build with Docker
        run:  sh build-docker.sh